name: Release Build

on:
    push:
        branches:
            - master

jobs:
    build:
        name: Build and Release
        runs-on: ubuntu-latest

        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]

        steps:
            - name: Check out the code
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.23

            - name: Build for ${{ matrix.os }}
              run: go build -o yap-${{ matrix.os }} main.go

            - name: Bump Version and Tag
              id: version
              run: |
                  git fetch --tags
                  version=$(git describe --tags $(git rev-list --tags --max-count=1))
                  IFS='.' read -r major minor patch <<< "${version#v}"
                  new_version="v$major.$minor.$((patch + 1))"
                  git tag $new_version
                  git push origin $new_version
              shell: bash

            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                  name: yap-${{ matrix.os }}
                  path: yap-${{ matrix.os }}

    release:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      yap-ubuntu-latest
                      yap-macos-latest
                      yap-windows-latest
                  draft: false
                  prerelease: false
